### PR TITLE
a basic app example

### PR DESCRIPTION
**Pull request by snelhest1337**
This can probably not be merged but I have no idea how to test this locally. It is close to but not entierly complete (need to write some more general stuff on connection between rails actions and corresponding HTTP requests), but some feedback would be nice

### CODE REVIEW

**Comment by snelhest1337** [comment]
I was very tired and wrote this in one sitting please be nice

**Comment by Lullebullelukas** [comment]
lgtm, can't be arsed to try on my machine lets just merge it lol

**Comment by Lullebullelukas** [comment]
oops did'nt read the "did not test it" part lol, oh well let's see what happens

**Comment by Lullebullelukas** [comment]
Ok so it looks good it just doesn't produce the right link,

to test: Issue make html into the terminal then use the live server vscode extension :

https://stackoverflow.com/questions/30039512/how-to-view-an-html-file-in-the-browser-with-visual-studio-code

**Pull request merged**
